//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.Note.App.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.Note.App.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Add120 {
            get {
                object obj = ResourceManager.GetObject("Add120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Add144 {
            get {
                object obj = ResourceManager.GetObject("Add144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Add192 {
            get {
                object obj = ResourceManager.GetObject("Add192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Add240 {
            get {
                object obj = ResourceManager.GetObject("Add240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Close120 {
            get {
                object obj = ResourceManager.GetObject("Close120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Close144 {
            get {
                object obj = ResourceManager.GetObject("Close144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Close192 {
            get {
                object obj = ResourceManager.GetObject("Close192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Close240 {
            get {
                object obj = ResourceManager.GetObject("Close240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   全 {0:#,0} 文字（{1:#,0} 行） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CountFormat {
            get {
                return ResourceManager.GetString("CountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy/MM/dd HH:mm 作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreationFormat {
            get {
                return ResourceManager.GetString("CreationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のノート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CurrentNote {
            get {
                return ResourceManager.GetString("CurrentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CubeNote のデータを保存するためのフォルダを選択して下さい。この変更は、アプリケーションの次回起動時から適用されます。また、現在のフォルダに存在するデータは新しいフォルダにはコピーされません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataFolderDescription {
            get {
                return ResourceManager.GetString("DataFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグの追加と削除 ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditTag {
            get {
                return ResourceManager.GetString("EditTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無題のページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmptyPage {
            get {
                return ResourceManager.GetString("EmptyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのノート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EveryoneTag {
            get {
                return ResourceManager.GetString("EveryoneTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Export120 {
            get {
                object obj = ResourceManager.GetObject("Export120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Export144 {
            get {
                object obj = ResourceManager.GetObject("Export144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Export192 {
            get {
                object obj = ResourceManager.GetObject("Export192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Export240 {
            get {
                object obj = ResourceManager.GetObject("Export240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Font {
            get {
                object obj = ResourceManager.GetObject("Font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Font120 {
            get {
                object obj = ResourceManager.GetObject("Font120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Font144 {
            get {
                object obj = ResourceManager.GetObject("Font144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Font192 {
            get {
                object obj = ResourceManager.GetObject("Font192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Font240 {
            get {
                object obj = ResourceManager.GetObject("Font240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   CubeNote に取り込むファイルを選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportTitle {
            get {
                return ResourceManager.GetString("ImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy/MM/dd HH:mm 更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LastUpdateFormat {
            get {
                return ResourceManager.GetString("LastUpdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Left {
            get {
                object obj = ResourceManager.GetObject("Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Left120 {
            get {
                object obj = ResourceManager.GetObject("Left120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Left144 {
            get {
                object obj = ResourceManager.GetObject("Left144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Left192 {
            get {
                object obj = ResourceManager.GetObject("Left192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Left240 {
            get {
                object obj = ResourceManager.GetObject("Left240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Logo120 {
            get {
                object obj = ResourceManager.GetObject("Logo120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Logo144 {
            get {
                object obj = ResourceManager.GetObject("Logo144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Logo192 {
            get {
                object obj = ResourceManager.GetObject("Logo192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Logo240 {
            get {
                object obj = ResourceManager.GetObject("Logo240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap LogoLarge {
            get {
                object obj = ResourceManager.GetObject("LogoLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Maximize {
            get {
                object obj = ResourceManager.GetObject("Maximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Maximize120 {
            get {
                object obj = ResourceManager.GetObject("Maximize120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Maximize144 {
            get {
                object obj = ResourceManager.GetObject("Maximize144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Maximize192 {
            get {
                object obj = ResourceManager.GetObject("Maximize192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Maximize240 {
            get {
                object obj = ResourceManager.GetObject("Maximize240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り取り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuCut {
            get {
                return ResourceManager.GetString("MenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDown {
            get {
                return ResourceManager.GetString("MenuDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノートを複製 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuDuplicate {
            get {
                return ResourceManager.GetString("MenuDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インターネットで検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuGoogle {
            get {
                return ResourceManager.GetString("MenuGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuImport {
            get {
                return ResourceManager.GetString("MenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいノート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuNewPage {
            get {
                return ResourceManager.GetString("MenuNewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノートにタグを設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuProperty {
            get {
                return ResourceManager.GetString("MenuProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   やり直し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRedo {
            get {
                return ResourceManager.GetString("MenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuRemove {
            get {
                return ResourceManager.GetString("MenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSearch {
            get {
                return ResourceManager.GetString("MenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuSelectAll {
            get {
                return ResourceManager.GetString("MenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元に戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuUp {
            get {
                return ResourceManager.GetString("MenuUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Minimize {
            get {
                object obj = ResourceManager.GetObject("Minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Minimize120 {
            get {
                object obj = ResourceManager.GetObject("Minimize120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Minimize144 {
            get {
                object obj = ResourceManager.GetObject("Minimize144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Minimize192 {
            get {
                object obj = ResourceManager.GetObject("Minimize192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Minimize240 {
            get {
                object obj = ResourceManager.GetObject("Minimize240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ニュース： {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewsFormat {
            get {
                return ResourceManager.GetString("NewsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Normalize {
            get {
                object obj = ResourceManager.GetObject("Normalize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Normalize120 {
            get {
                object obj = ResourceManager.GetObject("Normalize120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Normalize144 {
            get {
                object obj = ResourceManager.GetObject("Normalize144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Normalize192 {
            get {
                object obj = ResourceManager.GetObject("Normalize192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Normalize240 {
            get {
                object obj = ResourceManager.GetObject("Normalize240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   未整理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NothingTag {
            get {
                return ResourceManager.GetString("NothingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カーソル {0:#,0} 行 {1:#,0} 列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PositionFormat {
            get {
                return ResourceManager.GetString("PositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Print120 {
            get {
                object obj = ResourceManager.GetObject("Print120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Print144 {
            get {
                object obj = ResourceManager.GetObject("Print144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Print192 {
            get {
                object obj = ResourceManager.GetObject("Print192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Print240 {
            get {
                object obj = ResourceManager.GetObject("Print240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Property {
            get {
                object obj = ResourceManager.GetObject("Property", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Property120 {
            get {
                object obj = ResourceManager.GetObject("Property120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Property144 {
            get {
                object obj = ResourceManager.GetObject("Property144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Property192 {
            get {
                object obj = ResourceManager.GetObject("Property192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Property240 {
            get {
                object obj = ResourceManager.GetObject("Property240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Redo120 {
            get {
                object obj = ResourceManager.GetObject("Redo120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Redo144 {
            get {
                object obj = ResourceManager.GetObject("Redo144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Redo192 {
            get {
                object obj = ResourceManager.GetObject("Redo192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Redo240 {
            get {
                object obj = ResourceManager.GetObject("Redo240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Remove {
            get {
                object obj = ResourceManager.GetObject("Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Remove120 {
            get {
                object obj = ResourceManager.GetObject("Remove120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Remove144 {
            get {
                object obj = ResourceManager.GetObject("Remove144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Remove192 {
            get {
                object obj = ResourceManager.GetObject("Remove192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Remove240 {
            get {
                object obj = ResourceManager.GetObject("Remove240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   すべてを置換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReplaceAll {
            get {
                return ResourceManager.GetString("ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 件を置換しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReplaceAllSuccess {
            get {
                return ResourceManager.GetString("ReplaceAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次を置換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReplaceNext {
            get {
                return ResourceManager.GetString("ReplaceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Search120 {
            get {
                object obj = ResourceManager.GetObject("Search120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Search144 {
            get {
                object obj = ResourceManager.GetObject("Search144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Search192 {
            get {
                object obj = ResourceManager.GetObject("Search192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Search240 {
            get {
                object obj = ResourceManager.GetObject("Search240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   次を検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchNext {
            get {
                return ResourceManager.GetString("SearchNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」 は見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchNotFound {
            get {
                return ResourceManager.GetString("SearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最後の検索結果まで到達しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchOver {
            get {
                return ResourceManager.GetString("SearchOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前を検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchPrev {
            get {
                return ResourceManager.GetString("SearchPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 個のノートが見つかりました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchSuccess {
            get {
                return ResourceManager.GetString("SearchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Settings120 {
            get {
                object obj = ResourceManager.GetObject("Settings120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Settings144 {
            get {
                object obj = ResourceManager.GetObject("Settings144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Settings192 {
            get {
                object obj = ResourceManager.GetObject("Settings192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Settings240 {
            get {
                object obj = ResourceManager.GetObject("Settings240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   タグを設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowProperty {
            get {
                return ResourceManager.GetString("ShowProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テキストファイル (*.txt)|*.txt;*.TXT|すべてのファイル (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextFilter {
            get {
                return ResourceManager.GetString("TextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Title {
            get {
                object obj = ResourceManager.GetObject("Title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Title120 {
            get {
                object obj = ResourceManager.GetObject("Title120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Title144 {
            get {
                object obj = ResourceManager.GetObject("Title144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Title192 {
            get {
                object obj = ResourceManager.GetObject("Title192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Title240 {
            get {
                object obj = ResourceManager.GetObject("Title240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   エクスポート (E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolMenuExport {
            get {
                return ResourceManager.GetString("ToolMenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノート一覧を非表示 (H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolMenuHide {
            get {
                return ResourceManager.GetString("ToolMenuHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーマニュアルを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolMenuLogo {
            get {
                return ResourceManager.GetString("ToolMenuLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷 (P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolMenuPrint {
            get {
                return ResourceManager.GetString("ToolMenuPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   やり直し (Y) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolMenuRedo {
            get {
                return ResourceManager.GetString("ToolMenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 (F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolMenuSearch {
            get {
                return ResourceManager.GetString("ToolMenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 (T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolMenuSettings {
            get {
                return ResourceManager.GetString("ToolMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元に戻す (Z) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolMenuUndo {
            get {
                return ResourceManager.GetString("ToolMenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノート一覧を表示 (H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolMenuVisible {
            get {
                return ResourceManager.GetString("ToolMenuVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Undo120 {
            get {
                object obj = ResourceManager.GetObject("Undo120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Undo144 {
            get {
                object obj = ResourceManager.GetObject("Undo144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Undo192 {
            get {
                object obj = ResourceManager.GetObject("Undo192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Undo240 {
            get {
                object obj = ResourceManager.GetObject("Undo240", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   http://www.cube-soft.jp/cubenote/update.php に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlUpdate {
            get {
                return ResourceManager.GetString("UrlUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://docs.cube-soft.jp/entry/cubenote に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlWeb {
            get {
                return ResourceManager.GetString("UrlWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このノートを削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarnRemove {
            get {
                return ResourceManager.GetString("WarnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノートの削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarnRemoveTitle {
            get {
                return ResourceManager.GetString("WarnRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグを削除しますか？キャンセルする場合は、「いいえ」を選択した後に「キャンセル」ボタンを押して下さい。
        ///
        ///この操作によって、タグ付されているノートが削除される事はありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarnTagRemove {
            get {
                return ResourceManager.GetString("WarnTagRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグの削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarnTagRemoveTitle {
            get {
                return ResourceManager.GetString("WarnTagRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたフォルダにファイルを書き込めませんでした。書き込み可能なフォルダを選択して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarnWritable {
            get {
                return ResourceManager.GetString("WarnWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CubeNote エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarnWritableTitle {
            get {
                return ResourceManager.GetString("WarnWritableTitle", resourceCulture);
            }
        }
    }
}
