//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cube.Note.App.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cube.Note.App.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyMenu {
            get {
                return ResourceManager.GetString("CopyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全 {0:#,0} 文字（{1:#,0} 行） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CountFormat {
            get {
                return ResourceManager.GetString("CountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy/MM/dd HH:mm 作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreationFormat {
            get {
                return ResourceManager.GetString("CreationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のノート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CurrentNote {
            get {
                return ResourceManager.GetString("CurrentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り取り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CutMenu {
            get {
                return ResourceManager.GetString("CutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DownMenu {
            get {
                return ResourceManager.GetString("DownMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノートを複製 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DuplicateMenu {
            get {
                return ResourceManager.GetString("DuplicateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグの追加と削除 ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditTag {
            get {
                return ResourceManager.GetString("EditTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無題のページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmptyPage {
            get {
                return ResourceManager.GetString("EmptyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのノート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EveryoneTag {
            get {
                return ResourceManager.GetString("EveryoneTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルに保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportMenu {
            get {
                return ResourceManager.GetString("ExportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Font {
            get {
                object obj = ResourceManager.GetObject("Font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   インターネットで検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GoogleMenu {
            get {
                return ResourceManager.GetString("GoogleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノート一覧を非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HideMenu {
            get {
                return ResourceManager.GetString("HideMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルからノートを作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportMenu {
            get {
                return ResourceManager.GetString("ImportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CubeNote に取り込むファイルを選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportTitle {
            get {
                return ResourceManager.GetString("ImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy/MM/dd HH:mm 更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LastUpdateFormat {
            get {
                return ResourceManager.GetString("LastUpdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Left {
            get {
                object obj = ResourceManager.GetObject("Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap LogoLarge {
            get {
                object obj = ResourceManager.GetObject("LogoLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Web ページへ移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogoMenu {
            get {
                return ResourceManager.GetString("LogoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Maximize {
            get {
                object obj = ResourceManager.GetObject("Maximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Minimize {
            get {
                object obj = ResourceManager.GetObject("Minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   新しいノートを作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewPageMenu {
            get {
                return ResourceManager.GetString("NewPageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Normalize {
            get {
                object obj = ResourceManager.GetObject("Normalize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   未整理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NothingTag {
            get {
                return ResourceManager.GetString("NothingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PasteMenu {
            get {
                return ResourceManager.GetString("PasteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カーソル {0:#,0} 行 {1:#,0} 列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PositionFormat {
            get {
                return ResourceManager.GetString("PositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Property {
            get {
                object obj = ResourceManager.GetObject("Property", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ノートにタグを設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PropertyMenu {
            get {
                return ResourceManager.GetString("PropertyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   やり直し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RedoMenu {
            get {
                return ResourceManager.GetString("RedoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Remove {
            get {
                object obj = ResourceManager.GetObject("Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveMenu {
            get {
                return ResourceManager.GetString("RemoveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてを置換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReplaceAll {
            get {
                return ResourceManager.GetString("ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 件を置換しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReplaceAllSuccess {
            get {
                return ResourceManager.GetString("ReplaceAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次を置換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReplaceNext {
            get {
                return ResourceManager.GetString("ReplaceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SearchEnd {
            get {
                object obj = ResourceManager.GetObject("SearchEnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchMenu {
            get {
                return ResourceManager.GetString("SearchMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次を検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchNext {
            get {
                return ResourceManager.GetString("SearchNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」 は見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchNotFound {
            get {
                return ResourceManager.GetString("SearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最後の検索結果まで到達しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchOver {
            get {
                return ResourceManager.GetString("SearchOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SearchPale {
            get {
                object obj = ResourceManager.GetObject("SearchPale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   前を検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchPrev {
            get {
                return ResourceManager.GetString("SearchPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 個のノートが見つかりました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchSuccess {
            get {
                return ResourceManager.GetString("SearchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectAllMenu {
            get {
                return ResourceManager.GetString("SelectAllMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   設定 (T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグを設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowProperty {
            get {
                return ResourceManager.GetString("ShowProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テキストファイル (*.txt)|*.txt;*.TXT|すべてのファイル (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextFilter {
            get {
                return ResourceManager.GetString("TextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Title {
            get {
                object obj = ResourceManager.GetObject("Title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   元に戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UndoMenu {
            get {
                return ResourceManager.GetString("UndoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpMenu {
            get {
                return ResourceManager.GetString("UpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノート一覧を表示 (H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VisibleMenu {
            get {
                return ResourceManager.GetString("VisibleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このノートを削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarnRemove {
            get {
                return ResourceManager.GetString("WarnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノートの削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarnRemoveTitle {
            get {
                return ResourceManager.GetString("WarnRemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://www.cube-soft.jp/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WebUrl {
            get {
                return ResourceManager.GetString("WebUrl", resourceCulture);
            }
        }
    }
}
